targets:
  $default:
    sources:
      exclude:
        - "example/**"
    builders:
      json_serializable:
        options:
          explicit_to_json: true
          any_map: true
          checked: false
